### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by jreinhardt** [torfuspolymorphus/coba#3]
Hi,

when running the tests, I get two failures:

    (venv)jreinhardt@jreinhardt-mobile:~/Software/coba$ ./runtests.py 
    ......FF............
    ======================================================================
    FAIL: test_coba.Test_Coba.test_restore_file_in_place
    ----------------------------------------------------------------------

    Traceback (most recent call last):
      File "/home/jreinhardt/Software/coba/venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/jreinhardt/Software/coba/test/test_coba.py", line 176, in test_restore_file_in_place
        eq(len(revs), 2)
    AssertionError: 3 != 2
    
    ======================================================================
    FAIL: test_coba.Test_Coba.test_restore_file_other_dir
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/jreinhardt/Software/coba/venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/jreinhardt/Software/coba/test/test_coba.py", line 203, in test_restore_file_other_dir
    eq(len(revs), 2)
    AssertionError: 3 != 2

    ----------------------------------------------------------------------
    Ran 20 tests in 30.007s

    FAILED (failures=2)

Keep up the good work!

**Comment by torfuspolymorphus** [comment]
The tests are a little susceptible to timing issues: On the one hand, the underlying file system events need some time to reach Coba, on the other hand we don't want our test  cases to take too long. I suspect that this is the cause for your failing tests.

Since your report I've increased the default wait time in the tests, could you simply try again? If the issue persists, can you please increase the default wait time in `Test_Coba.wait` in `test/test_coba.py` and check if that resolves the issue? If so, what waiting time do you need for the tests to pass?

**Comment by jreinhardt** [comment]
The tests pass now (and there are more of them as well)

**Comment by torfuspolymorphus** [comment]
Perfect, thanks for your feedback!
